#!/usr/bin/env bash
#update package list
apt-get update -y

#install nginx silently

apt-get install nginx -y

#create html content
echo "<html><head></head><body>Holberton School for the win!</body></html>" > /var/www/html/index.html

# Restart nginx using service(not systemctl)
service nginx restart
