#!/usr/bin/env bash
#update package list
apt-get update -y

#install nginx silently

apt-get install nginx -y

#create html content
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Restart nginx using service(not systemctl)
service nginx restart
