#!/usr/bin/env bash
#update package list
apt-get update -y

#install nginx silently

apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'

#create html content
sh -c 'echo "Holberton School" > /var/www/html/index.html'

# Restart nginx using service(not systemctl)
service nginx restart
